
{{- /* ────────────────────────────────────────────────────────────────
    rendered only if persistence.create is true
   ──────────────────────────────────────────────────────────────── */ -}}
{{- if and .Values.postgres.enabled .Values.postgres.persistence.enabled .Values.postgres.persistence.pvc_create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: {{ .Values.postgres.persistence.storageClassName }}
  accessModes: {{- toYaml .Values.postgres.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
{{- end }}
